Repository boostcampwm-2024/and04-Nature-Album, pull requests merged in 2024-11, with the labels that each got.

#69 카메라 권한 허용 후 카메라 시작
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/component/MyDialog.kt
  app/src/main/java/com/and04/naturealbum/ui/component/RoundedShapeButton.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/home/RequestPermission.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/Label.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/res/drawable/cat_dummy.jpg
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#83 Room Database 추가 및 Hilt 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/NatureAlbum.kt
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/AppDatabase.kt
  app/src/main/java/com/and04/naturealbum/data/room/Data.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#84 [Fix] Repository Hilt Error
  app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
Labels: bug

#85 사진 저장화면 내비게이션
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/component/MyTopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/home/RequestPermission.kt
  app/src/main/java/com/and04/naturealbum/ui/home/permissionHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
Labels: enhancement

#88 도감 등록창에서 라벨 검색 기능 추가
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelColor.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/Label.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#87 Album Screen 구현 및 Navigation 연결
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/data/dto/DataDto.kt
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/utils/Utils.kt
  app/src/main/res/drawable/sample_image_01.JPG
  app/src/main/res/drawable/sample_image_02.JPG
  gradle/libs.versions.toml
Labels: enhancement

#91 사진 상세 화면에서 DB에 저장
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
Labels: enhancement

#100 사진 상세 저장 + GPS관련
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/AppDatabase.kt
  app/src/main/java/com/and04/naturealbum/data/room/Converters.kt
  app/src/main/java/com/and04/naturealbum/data/room/Data.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/ui/LocationHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/component/MyDialog.kt
  app/src/main/java/com/and04/naturealbum/ui/component/RoundedShapeButton.kt
  app/src/main/java/com/and04/naturealbum/ui/home/GPSHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/PermissionDialogs.kt
  app/src/main/java/com/and04/naturealbum/ui/home/PermissionHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#105 익명 회원 로그인 추가
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
Labels: enhancement

#108 AuthenticationManager 리펙토링
  app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
Labels: enhancement

#111 메인,도감화면 configuration change 대응
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/component/ClippingButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/MyTopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/component/NavigationImageButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
Labels: enhancement

#115 지도, ImageMarker 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/NatureAlbum.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/ImageMarker.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreenViewModel.kt
  app/src/main/res/drawable/ic_empty_marker.xml
  app/src/main/res/layout/image_marker.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#116 [SacePhotoScreen] ConfigurationChange 대응
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/component/AlbumLabel.kt
  app/src/main/java/com/and04/naturealbum/ui/component/ClippingButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/NavigationImageButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
  app/src/main/java/com/and04/naturealbum/utils/ComposeUtils.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#118 [Fix] map theme error 해결
  app/src/main/res/values/themes.xml
Labels: bug

#120 [Fix] 중복 라벨 생성 방지
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug

#125 UI 버그 수정 및 도감 저장 UI에 배경 수정
  app/src/main/java/com/and04/naturealbum/ui/component/BackgroundImage.kt
  app/src/main/java/com/and04/naturealbum/ui/component/ClippingButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/MyTopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/component/RoundedShapeButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/res/drawable/drawable_background_image_bottom_start.xml
  app/src/main/res/drawable/drawable_background_image_top_end.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#127 [Fix] viewModel과 기타 문제로 인해 Preview가 안보이던 버그 수정
  app/src/main/java/com/and04/naturealbum/data/room/Data.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderState.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/LabelWithButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/ClippingButton.kt
  app/src/main/java/com/and04/naturealbum/ui/component/RotatingAnimation.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/utils/DummyUtils.kt
Labels: bug, enhancement

#141 화면 전환 시 리컴포지션이 불필요하게 일어나는 로직 개선
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderState.kt
Labels: enhancement

#139 마이페이지 로그인 시 친구 목록, 친구 검색, 알림 UI 구현
  app/src/main/java/com/and04/naturealbum/data/dto/MyFriend.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#138 이미지 리사이징
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/NatureAlbum.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/utils/ImageConvert.kt
  gradle/libs.versions.toml
Labels: enhancement

#144 마커 클러스터링
  app/src/main/java/com/and04/naturealbum/ui/LocationHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/ImageMarker.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/PhotoKey.kt
  app/src/main/java/com/and04/naturealbum/utils/SvgParser.kt
  app/src/main/res/drawable/ic_cluster.xml
Labels: enhancement

#147 Firestore NoSQL 설계 및 친구 관리 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/data/dto/FirebaseDto.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
  app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendTestScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#149 WorkManager를 이용한 정각에 동기화 작업 - 1차
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/NatureAlbum.kt
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseInsertService.kt
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/dto/DataDto.kt
  app/src/main/java/com/and04/naturealbum/data/dto/RoomDataDto.kt
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  gradle/libs.versions.toml
Labels: enhancement

#157 서버 필터링을 통한 친구 검색 기능 구현 및 UI 구성 변경
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
Labels: enhancement

#153 마이페이지에 동기화 UI 추가
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/utils/NetworkState.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#151 클러스터 틴트 및 텍스트 추가
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
Labels: enhancement

#154 Hilt로 기존 코드 개선
  app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
Labels: refactoring

#155 좌표계를 도로명 주소로 변환
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/data/dto/ReverseGeocodeDto.kt
  app/src/main/java/com/and04/naturealbum/data/repository/ReverseGeocodeRepository.kt
  app/src/main/java/com/and04/naturealbum/data/retorifit/ReverseGeocodeAPI.kt
  app/src/main/java/com/and04/naturealbum/data/retorifit/ReverseGeocodeAPIFactory.kt
  app/src/main/java/com/and04/naturealbum/di/ReverseGeocodeModule.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement

#163 [Fix] conflict 해결 과정에서 발생한 버그 수정
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoViewModel.kt
Labels: bug

#159 즉시 동기화 기능 구현
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
Labels: enhancement

#171 동기화 시간 저장 및 UI 표시
  app/build.gradle.kts
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/datastore/DataStoreManager.kt
  app/src/main/java/com/and04/naturealbum/di/DataStoreModule.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/test/java/com/and04/naturealbum/ExampleUnitDataStoreManager.kt
  gradle/libs.versions.toml
Labels: enhancement

#168 양방향 동기화
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseInsertService.kt
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/dto/FirebaseDto.kt
  app/src/main/java/com/and04/naturealbum/data/dto/RoomDataDto.kt
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
Labels: enhancement

#169 로그인 오류 - 이전 Hilt로 Context 주입 원상복구
  app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
Labels: bug

#175 [Fix] Service에서 토스트 제거
  app/src/main/java/com/and04/naturealbum/service/FirebaseInsertService.kt
Labels: bug

#177 친구 기능 탭 내용 UI 실시간 업데이트 및 배지 표시 기능 추가
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendTestScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
Labels: enhancement, refactoring

#176 Gemini API 로직 변경
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, refactoring

#179 NatureAlbumApp Navigation 리펙토링
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
Labels: refactoring

#180 Gemini API 로직 개선 & Compose Navigation 리펙토링
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, refactoring

#183 [Fix] Theme 적용
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
Labels: bug

#164 친구 지도 함께보기
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseInsertService.kt
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/ClusterManager.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreenViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/PhotoKey.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/utils/TimeUtils.kt
  app/src/main/res/drawable/ic_cluster.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#184 [Fix] map 이동 시 앱 꺼짐 해결
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
Labels: bug

#190 [Fix] merge error
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
Labels: bug

#189 네트워크 상태 기반 MyPage UI 동적 변경 및 로그인 네트워크 확인 기능 추가
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/PermissionHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/utils/NetworkManager.kt
  app/src/main/java/com/and04/naturealbum/utils/NetworkViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, refactoring

#195 MyPage 친구 기능 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/service/FirebaseMessagingService.kt
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/PermissionHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendTestScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreenViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/and04/naturealbum/utils/NetworkManager.kt
  app/src/main/java/com/and04/naturealbum/utils/NetworkViewModel.kt
  app/src/main/res/values/strings.xml
  firebase/.firebaserc
  firebase/.gitignore
  firebase/firebase.json
  firebase/firestore.indexes.json
  firebase/firestore.rules
  firebase/functions/.gitignore
  firebase/functions/index.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
  gradle/libs.versions.toml
Labels: enhancement

#191 대표 이미지 변경 기능 & 가로모드 세로모드 파일 분리
  app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, refactoring

#196 [Fix] 서버에 라벨 없이 사진 정보만 들어가는 오류 해결
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseInsertService.kt
Labels: bug

#186 [동기화] 라벨 중복 시 로컬 라벨로 서버에 업데이트
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/dto/FirebaseDto.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
Labels: enhancement

#185 지도 화면 bottomSheet 사용성 개선
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/component/PatialBottomSheet.kt
  app/src/main/java/com/and04/naturealbum/ui/component/RotatingAnimation.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreenViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/PhotoKey.kt
  app/src/main/res/drawable/ic_butterfly_white.xml
  app/src/main/res/drawable/ic_butterfly_yellow.xml
  app/src/main/res/drawable/ic_cat.xml
  app/src/main/res/drawable/ic_dog.xml
  app/src/main/res/drawable/ic_fish_orange.xml
  app/src/main/res/drawable/ic_fish_red.xml
Labels: enhancement

#198 [Fix] 마이페이지에서 바로 홈화면 가는 것이 아닌 popBackStack으로 가도록 수정
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
Labels: bug

#199 [Feat] app logo 추가 및 설정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_main-playstore.png
  app/src/main/res/drawable/ic_main_background.xml
  app/src/main/res/drawable/ic_main_foreground.xml
  app/src/main/res/drawable/logo_nature_album.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_round.xml
  app/src/main/res/mipmap-hdpi/ic_main.webp
  app/src/main/res/mipmap-hdpi/ic_main_round.webp
  app/src/main/res/mipmap-mdpi/ic_main.webp
  app/src/main/res/mipmap-mdpi/ic_main_round.webp
  app/src/main/res/mipmap-xhdpi/ic_main.webp
  app/src/main/res/mipmap-xhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_round.webp
Labels: enhancement

#201 [Fix] MyPage 팅기는 오류 해결
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
Labels: bug

#193 로그인 할 때 프로그래스바, 동기화 할 떄 애니메이션 추가
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/ui/component/ProgressIndicator.kt
  app/src/main/java/com/and04/naturealbum/ui/component/RotatingIconButton.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement
