Repository boostcampwm-2024/and04-Nature-Album, pull requests merged in 2024-12, with the labels that each got.

#219 [Fix] 위치 꺼져 있을 때 사진 찍으면 앱 터짐
  app/src/main/java/com/and04/naturealbum/ui/LocationHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenPortrait.kt
Labels: bug

#220 [Fix] 비행기 모드일 때 카메라 미동작
  app/src/main/java/com/and04/naturealbum/ui/LocationHandler.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug

#224 [Feature/Refactor] 친구 검색 화면 개선 및 피드백 반영
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseMessagingService.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageItems.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumDestination.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, refactoring

#223 네비게이션 관련 버그 수정
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
Labels: bug

#231 도감 비었을 때 Text로 알려주는 UI & TopBar & Google 로그인 버튼 개선 작업
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/utils/ComposeUtils.kt
  app/src/main/res/drawable/ic_google_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactoring

#222 DataSource와 Repository 분리 및 네트워크 예외처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseInsertService.kt
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseMessagingService.kt
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/datasource/FirebaseDataSource.kt
  app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/firebase/AlbumRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/firebase/FriendRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/firebase/UserRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/LocalDataRepository.kt
  app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
  app/src/main/java/com/and04/naturealbum/di/FirebaseModule.kt
  app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
  app/src/main/java/com/and04/naturealbum/ui/album/AlbumViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreenViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
  app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfoViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
Labels: refactoring

#246 상태바 색상 수정
  app/src/main/java/com/and04/naturealbum/ui/theme/Theme.kt
Labels: refactoring

#250 지도 화면 백버튼 추가
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#252 친구 요청 성공 여부 토스트 메세지 및 Push알림 MyPage로 딥링크
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/and04/naturealbum/background/service/FirebaseMessagingService.kt
  app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
  app/src/main/res/values/strings.xml
  firebase/functions/index.js
Labels: enhancement, refactoring

#254 [Fix] 지도화면 bottom sheet 라벨 텍스트 멀티라인 제거
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
Labels: enhancement

#256 데이터 상태에서 수동 동기화 미작동
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
Labels: bug
